apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: perf-sidecar
        image: bpradipt/perf:4.4
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        securityContext:
            privileged: true
    ShareProcessNamespace: true
